server:
  port: ${SERVER_PORT}
  allowOrigin: ${ALLOW_ORIGIN}

database:
  driver: "postgres"
  host: ${DB_HOST}
  port: 5432
  user: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}
  sslmode: "disable"
  maxIdle: 10
  maxConn: 25
  maxLife: 1