version: "2"
sql:
  - engine: "postgresql"
    schema: "database/migrations/"
    queries: "database/query/"
    gen:
      go:
        package: "models"
        out: "models"
        emit_json_tags: true
        emit_interface: true
        emit_empty_slices: true